### ISSUE TITLE
[DEV] AndroidStudioの開発環境を構築する

### ISSUE THREAD

**Issue by tiki-torches** [tiki-torches/JotGPS#1]
# Goal
- [x] AndroidStudioのエミュレーター上でHelloWorldが表示されること

**Comment by tiki-torches** [comment]
## AndroidStudioをインストールする
[配布ページ](https://developer.android.com/studio)よりAndroidStudio(Ver. Flamingo | 2022.2.1)を取得する。
インストール時の設定は任意でOK。AndroidStudio(以下、AS)の起動を確認できればOK。

## 初期プロジェクトを作成する
AS標準で用意されているテンプレートからプロジェクトを生成する。
`New Projects > Phone and Tablet > Basic Views Activity`を選択する。

![image](https://user-images.githubusercontent.com/122960484/236591498-f847ced4-1cb6-4501-ab88-5e5b26ad0f9b.png)

プロジェクトの名前やMinimum SDKの指定を設定する。
Minimum SDKとは、動作環境に必要な最低限のOSのバージョンのこと。要するにここで指定されたバージョン以下の端末ではユーザーは本アプリを使用できない（なんならGppglePlayでインストールすらできないらしい。かなしい）。
![image](https://user-images.githubusercontent.com/122960484/236591349-f55db307-89fa-4f5a-9fc6-b3a97e593de2.png)

2023年1月現在、バージョンごとのシェア率は以下の分布とのこと。
~~8割超えていれば本プロジェクトとしてはOK…ということにしてMinimum SDKは9を指定。~~
[GooglePlayの方針](https://developer.android.com/distribute/best-practices/develop/target-sdk?hl=JA)として、最新バージョンを指定しなければストアに公開できないとのこと。したがって現時点で最新の13.0を指定。問答無用で。
![image](https://user-images.githubusercontent.com/122960484/236591646-761685e5-2d99-4c15-a332-754461a19268.png)

各種初期ファイルが生成され、以下のファイル構成となっていることを確認できればOK。
![image](https://user-images.githubusercontent.com/122960484/236592055-d67e9207-abab-4afb-bccf-fd93d4b6e920.png)

**Comment by tiki-torches** [comment]
## アプリを実行する
ヘッダ上の`Run > Run app`(またはショートカット`Shift + F10`)でandroid端末のエミュレーションを開始しアプリを実行する。AS上で以下のようにアプリが表示されればOK



https://developer.android.com/distribute/best-practices/develop/target-sdk?hl=JA

**Comment by tiki-torches** [comment]
## Githubにソースコードをアップロードする
[参考](https://qiita.com/TAKANEKOMACHI/items/0101f0ff88fad2696e81)

大まかには、ASにGithubが発行する認証情報（トークン）を埋め込むことでASとGithub間のやりとりが可能になる。

まずはトークンの発行を行う。
Github上のプロフィール設定を開き`Settings > Developer Settings > Personal access tokens > Tokens (classic)`
トークンの寿命や権限範囲など設定可能だが、今回は特に縛らず永遠 & 全権限を付与（本当はやめたほうがいい）。
文字列が生成されるのでコピー。

gitを使用する旨をASに設定する。ASのヘッダ`VCS > Enable VCSなんとかかんとか`を押下し、`git`を選択。
それまで`VCS`表記であった部分が`Git`に変わればOK。

ついにトークンを埋め込む。
`Git > Github > Share Project On Github > Add Account > Token`を選択。
先ほど発行した文字列を入力する。特にエラーが起きなければOK。
![image](https://user-images.githubusercontent.com/122960484/236604982-ab1185ff-41bb-4b2a-89ac-3db103db67f1.png)

最後に、gitにアプリをアップロードする。
`Git > Share On Github`でエラーが起きなければOK。

**Comment by tokio275** [comment]
AndroidStudioをインストール後、上の手順でファイルを確認するところまで進めたのですがRun appを入力すると下のように画像が表示され表示されません...　最初の設定等で間違いがあったのでしょうか...
いろいろ試してみます。

![スクリーンショット 2023-05-11 201639](https://github.com/tiki-torches/JotGPS/assets/113747182/b97986b1-0fc6-4ca2-bf66-dd49acce24f3)

**Comment by nnkystk** [comment]
@tokio275 
利用者側で原因判断できる情報ないですね。。。

もしかしたらgithubからクローンしたファイルとの相性の問題もあるかもなので、新規プロジェクトをテンプレートから生成して動かしてみるのも手です。

**Comment by nnkystk** [comment]
@tokio275 
もし未解消だったら左下のshow details押してみて出てくる情報を共有してもらえれば…何かわかる…かも

**Comment by tokio275** [comment]
```
Operating system: Windows NT
                  10.0.22621 1702
CPU: amd64
     family 6 model 140 stepping 1
     8 CPUs

GPU: UNKNOWN

Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0x0
Process uptime: 20 seconds

Thread 0 (crashed)
```

また
![スクリーンショット 2023-05-12 092951](https://github.com/tiki-torches/JotGPS/assets/113747182/b503eaab-b873-4efd-8f7c-a362b12d0e8a)
とも表示されます。パソコンのストレージ不足かもしれないので軽くしてやってみます。

**Comment by tokio275** [comment]
先ほど容量を少し軽くしたところ
![スクリーンショット 2023-05-12 102902](https://github.com/tiki-torches/JotGPS/assets/113747182/a3728ea0-1e7b-4a4b-83d6-f019bc3fde61)
の画面になりその後
![スクリーンショット 2023-05-12 103020](https://github.com/tiki-torches/JotGPS/assets/113747182/9b428bbe-0fe7-45b0-93f1-6962c599a183)
の画面になりました。やはりパソコンの容量不足で起動できなかった可能性高いです。

**Comment by nnkystk** [comment]
素晴らしい

**Comment by tokio275** [comment]
![スクリーンショット 2023-05-13 152533](https://github.com/tiki-torches/JotGPS/assets/113747182/90d1b3e4-4cb6-459e-a9d4-292181fe8731)
githubにアップしました。これで問題ないでしょうか？

**Comment by tiki-torches** [comment]
@tokio275 
大丈夫です🦀  
(ASとgithubの連携確認、という意味であれば)

念のため補足説明すると、いまやってもらったのは
「①新たに作成したファイルを ②自分で新規作成したtokio/shioリポジトリにアップする」という処理です。
※ リポジトリ ≒ プロジェクト

これからは「①変更を加えた差分のみを ②tiki-torches/JotGPSリポジトリにアップする」という処理をやっていきます。
詳しくは具体的にissueを消化するときに改めて共有しますが、もし変更をアップしたのに反映されない…！という事態が発生したらtokio/shioのほうへアップしてしまっている可能性アリです。

**Comment by tokio275** [comment]
承知いたしました。
